### ISSUE TITLE
footer-notes-misplacement false positive

### ISSUE THREAD

**Issue by knocte** [nblockchain/conventions#107]
See https://github.com/nodeeffect/RunIntoMe/actions/runs/4797635782/jobs/8534872563

Culprit: https://github.com/nodeeffect/RunIntoMe/commit/a643823f492c7a54cff35e70c1cdc30aa17da4cc

**Comment by parhamsaremi** [comment]
I'm not sure putting ``` in the footer is a good idea. My understanding was that the footer is for small stuff maybe a link or a hash or something like this. and footers [] should be the last thing that is proposed in a commit message.

I'm not saying that this is really better but I think allowing long footers in the long run might cause us with bad-looking commit messages 🤔 here's how I would write this commit message as a part of the body.

Frontend: better approach for text re-style

The previous approach implemented in [1] may have been
not very performant, plus this approach breaks at build
time in case the specified element doesn't exist in the
Texts class, with the error below instead of a runtime crash such as [2].

```
Frontend/MainPage.xaml(17,17): Error XFC0101: x:Static: unable to find a public -- or accessible internal -- static field, static property, const or enum value named "WelcomeTexts" in "app:Texts". (XFC0101) (Frontend) XamlC
```

[1] e8577d41e67b8a97dfd41d31cf44294a5da9bef8
[2] https://nblockchain.sentry.io/issues/4110061816/

**Comment by knocte** [comment]
Fair enough.
