### ISSUE TITLE
body-soft-max-line-length exception

### ISSUE THREAD

**Issue by knocte** [nblockchain/conventions#124]
This rule should not break the build if the offending line exceeds 64 chars because it uses a commit hash at the end.

Testcase:
```
GrpcService: fix some logging nits

These mistakes were made in 45faeca2f0e7c9c5545f54fb3fcc815f52b8a7cf.
```

Testcase that should still break the build (because line is longer than 64 chars before the commit hash):
```
GrpcService: fix some logging nits

These mistakes were made in this GrpcService's RunIntoMeService commit: 45faeca2f0e7c9c5545f54fb3fcc815f52b8a7cf.
```

**Comment by realmarv** [comment]
@webwarrior-ws please work on this issue if you are taskless.

**Comment by knocte** [comment]
@realmarv I think @webwarrior-ws got stuck with this task, I don't remember his reasoning. Please pair with him on it after he's done with his NLitecoin low-prio task.
