### ISSUE TITLE
footer-refs-validity false positive

### ISSUE THREAD

**Issue by knocte** [nblockchain/conventions#125]
From https://github.com/nodeffectLtd/RunIntoMe/actions/runs/5530782872/jobs/10090619696. Commit msg: https://github.com/nodeffectLtd/RunIntoMe/commit/d4cc624cc95d237686e55ba6317efb9f0b791cfd

**Comment by webwarrior-ws** [comment]
Message body contains lines with text like `Jul 12 10:58:47 vultr env[2647]:`, in which `[2647]` gets recognized as a reference.
Perhaps body string needs to be stripped of text between triple backticks (` ``` `). Maybe even single backticks?

**Comment by knocte** [comment]
> Maybe even single backticks?

No, just triple backticks. Other rules already do this (removing triple-backticks codeblocks) before analyzing stuff, so you just have to copy their approach in this rule.

**Comment by knocte** [comment]
@webwarrior-ws Please note, @realmarv already has cooked a fix for this (see above linked PR in case you're curious).
