### ISSUE TITLE
spawnSync is not cross-platform

### ISSUE THREAD

**Issue by Mersho** [nblockchain/conventions#154]
### Steps To Reproduce:

1. On Windows: try to call the "runCommitLintOnMsg" function or debug a test to see the function results.

### Current Results:

'spawnSync npx ENOENT'

workaround (not recommended) :
https://stackoverflow.com/a/37138541

### Exepected Results:

Commitlint should be executed without errors.

**Comment by knocte** [comment]
Not recommended why?

**Comment by Mersho** [comment]
> Not recommended why?

My guess is: we might have related issues about this workaround in the future or the ".cmd" suffix may not work in all environments.

**Comment by knocte** [comment]
> or the ".cmd" suffix may not work in all environments.

If it doesn't work in all environments, then let's only use .cmd in Windows? Simple solution really.
