### ISSUE TITLE
Improve scripts/detectNotUsingGitPush1by1.fsx to detect broken(red) CI statuses

### ISSUE THREAD

**Issue by knocte** [nblockchain/conventions#95]
After detectNotUsingGitPush1by1.fsx checks that gitPush1by1 was used it should check CI status of each commit:
- If commit msg contains text "failing test", then it would be allowed to have broken CI.
- Else: CI should be green (and if it's not, then script should exit with ExitCode>0).

**Comment by realmarv** [comment]
I'm not sure if it's possible because while the script is running in the CI, the CI status is in_progress. Unless we force push CI runs to finish before starting pull_request CI runs (Not sure if it's possible either)

**Comment by knocte** [comment]
Let's make it for now that if it's red, it fails. If It's green or **in progress**, then it works.
